// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ug.domain;

import com.ug.domain.CorporateDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CorporateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CorporateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CorporateIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CorporateIntegrationTest: @Transactional;
    
    @Autowired
    private CorporateDataOnDemand CorporateIntegrationTest.dod;
    
    @Test
    public void CorporateIntegrationTest.testCountCorporates() {
        org.junit.Assert.assertNotNull("Data on demand for 'Corporate' failed to initialize correctly", dod.getRandomCorporate());
        long count = com.ug.domain.Corporate.countCorporates();
        org.junit.Assert.assertTrue("Counter for 'Corporate' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CorporateIntegrationTest.testFindCorporate() {
        com.ug.domain.Corporate obj = dod.getRandomCorporate();
        org.junit.Assert.assertNotNull("Data on demand for 'Corporate' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Corporate' failed to provide an identifier", id);
        obj = com.ug.domain.Corporate.findCorporate(id);
        org.junit.Assert.assertNotNull("Find method for 'Corporate' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Corporate' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CorporateIntegrationTest.testFindAllCorporates() {
        org.junit.Assert.assertNotNull("Data on demand for 'Corporate' failed to initialize correctly", dod.getRandomCorporate());
        long count = com.ug.domain.Corporate.countCorporates();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Corporate', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.ug.domain.Corporate> result = com.ug.domain.Corporate.findAllCorporates();
        org.junit.Assert.assertNotNull("Find all method for 'Corporate' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Corporate' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CorporateIntegrationTest.testFindCorporateEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Corporate' failed to initialize correctly", dod.getRandomCorporate());
        long count = com.ug.domain.Corporate.countCorporates();
        if (count > 20) count = 20;
        java.util.List<com.ug.domain.Corporate> result = com.ug.domain.Corporate.findCorporateEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Corporate' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Corporate' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CorporateIntegrationTest.testFlush() {
        com.ug.domain.Corporate obj = dod.getRandomCorporate();
        org.junit.Assert.assertNotNull("Data on demand for 'Corporate' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Corporate' failed to provide an identifier", id);
        obj = com.ug.domain.Corporate.findCorporate(id);
        org.junit.Assert.assertNotNull("Find method for 'Corporate' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCorporate(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Corporate' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CorporateIntegrationTest.testMerge() {
        com.ug.domain.Corporate obj = dod.getRandomCorporate();
        org.junit.Assert.assertNotNull("Data on demand for 'Corporate' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Corporate' failed to provide an identifier", id);
        obj = com.ug.domain.Corporate.findCorporate(id);
        boolean modified =  dod.modifyCorporate(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.ug.domain.Corporate merged = (com.ug.domain.Corporate) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Corporate' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CorporateIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Corporate' failed to initialize correctly", dod.getRandomCorporate());
        com.ug.domain.Corporate obj = dod.getNewTransientCorporate(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Corporate' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Corporate' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Corporate' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CorporateIntegrationTest.testRemove() {
        com.ug.domain.Corporate obj = dod.getRandomCorporate();
        org.junit.Assert.assertNotNull("Data on demand for 'Corporate' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Corporate' failed to provide an identifier", id);
        obj = com.ug.domain.Corporate.findCorporate(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Corporate' with identifier '" + id + "'", com.ug.domain.Corporate.findCorporate(id));
    }
    
}
