// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ug.domain;

import com.ug.domain.ProfileDataOnDemand;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProfileIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProfileIntegrationTest: @Transactional;
    
    @Autowired
    private ProfileDataOnDemand ProfileIntegrationTest.dod;
    
    @Test
    public void ProfileIntegrationTest.testCountProfiles() {
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to initialize correctly", dod.getRandomProfile());
        long count = com.ug.domain.Profile.countProfiles();
        org.junit.Assert.assertTrue("Counter for 'Profile' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProfileIntegrationTest.testFindProfile() {
        com.ug.domain.Profile obj = dod.getRandomProfile();
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to provide an identifier", id);
        obj = com.ug.domain.Profile.findProfile(id);
        org.junit.Assert.assertNotNull("Find method for 'Profile' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Profile' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProfileIntegrationTest.testFindAllProfiles() {
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to initialize correctly", dod.getRandomProfile());
        long count = com.ug.domain.Profile.countProfiles();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Profile', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.ug.domain.Profile> result = com.ug.domain.Profile.findAllProfiles();
        org.junit.Assert.assertNotNull("Find all method for 'Profile' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Profile' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProfileIntegrationTest.testFindProfileEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to initialize correctly", dod.getRandomProfile());
        long count = com.ug.domain.Profile.countProfiles();
        if (count > 20) count = 20;
        java.util.List<com.ug.domain.Profile> result = com.ug.domain.Profile.findProfileEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Profile' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Profile' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProfileIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to initialize correctly", dod.getRandomProfile());
        com.ug.domain.Profile obj = dod.getNewTransientProfile(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Profile' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Profile' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProfileIntegrationTest.testRemove() {
        com.ug.domain.Profile obj = dod.getRandomProfile();
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to provide an identifier", id);
        obj = com.ug.domain.Profile.findProfile(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Profile' with identifier '" + id + "'", com.ug.domain.Profile.findProfile(id));
    }
    
}
