// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ug.domain;

import com.ug.domain.Profile;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect ProfileDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProfileDataOnDemand: @Component;
    
    private Random ProfileDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Profile> ProfileDataOnDemand.data;
    
    public Profile ProfileDataOnDemand.getNewTransientProfile(int index) {
        com.ug.domain.Profile obj = new com.ug.domain.Profile();
        obj.setUserId(null);
        obj.setUniversityId(null);
        obj.setDepartmentId(null);
        obj.setProgramStudyId(null);
        obj.setGenderId(null);
        obj.setCitizenship(null);
        obj.setExpectedGraduationDate(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        obj.setDateOfBirth(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        java.lang.String homePhone = "homePhon_" + index;
        if (homePhone.length() > 10) {
            homePhone  = homePhone.substring(0, 10);
        }
        obj.setHomePhone(homePhone);
        java.lang.String linkedInProfile = "linkedInProfile_" + index;
        if (linkedInProfile.length() > 255) {
            linkedInProfile  = linkedInProfile.substring(0, 255);
        }
        obj.setLinkedInProfile(linkedInProfile);
        java.lang.String youtubeurl = "youtubeurl_" + index;
        if (youtubeurl.length() > 255) {
            youtubeurl  = youtubeurl.substring(0, 255);
        }
        obj.setYoutubeUrl(youtubeurl);
        java.lang.String mobile = "mobile_" + index;
        if (mobile.length() > 10) {
            mobile  = mobile.substring(0, 10);
        }
        obj.setMobile(mobile);
        java.lang.String photoIdentifier = "photoIdentifier_" + index;
        if (photoIdentifier.length() > 75) {
            photoIdentifier  = photoIdentifier.substring(0, 75);
        }
        obj.setPhotoIdentifier(photoIdentifier);
        java.lang.String resumeIdentifier = "resumeIdentifier_" + index;
        if (resumeIdentifier.length() > 75) {
            resumeIdentifier  = resumeIdentifier.substring(0, 75);
        }
        obj.setResumeIdentifier(resumeIdentifier);
        java.lang.String universityEmail = "universityEmail_" + index;
        if (universityEmail.length() > 255) {
            universityEmail  = universityEmail.substring(0, 255);
        }
        obj.setUniversityEmail(universityEmail);
        java.lang.String briefDescription = "briefDescription_" + index;
        if (briefDescription.length() > 500) {
            briefDescription  = briefDescription.substring(0, 500);
        }
        obj.setBriefDescription(briefDescription);
        return obj;
    }
    
    public Profile ProfileDataOnDemand.getSpecificProfile(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Profile obj = data.get(index);
        return Profile.findProfile(obj.getId());
    }
    
    public Profile ProfileDataOnDemand.getRandomProfile() {
        init();
        Profile obj = data.get(rnd.nextInt(data.size()));
        return Profile.findProfile(obj.getId());
    }
    
    public boolean ProfileDataOnDemand.modifyProfile(Profile obj) {
        return false;
    }
    
    public void ProfileDataOnDemand.init() {
        data = com.ug.domain.Profile.findProfileEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Profile' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.ug.domain.Profile>();
        for (int i = 0; i < 10; i++) {
            com.ug.domain.Profile obj = getNewTransientProfile(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
