// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ug.domain;

import com.ug.domain.UniversityDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UniversityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UniversityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UniversityIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: UniversityIntegrationTest: @Transactional;
    
    @Autowired
    private UniversityDataOnDemand UniversityIntegrationTest.dod;
    
    @Test
    public void UniversityIntegrationTest.testCountUniversitys() {
        org.junit.Assert.assertNotNull("Data on demand for 'University' failed to initialize correctly", dod.getRandomUniversity());
        long count = com.ug.domain.University.countUniversitys();
        org.junit.Assert.assertTrue("Counter for 'University' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UniversityIntegrationTest.testFindUniversity() {
        com.ug.domain.University obj = dod.getRandomUniversity();
        org.junit.Assert.assertNotNull("Data on demand for 'University' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'University' failed to provide an identifier", id);
        obj = com.ug.domain.University.findUniversity(id);
        org.junit.Assert.assertNotNull("Find method for 'University' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'University' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UniversityIntegrationTest.testFindAllUniversitys() {
        org.junit.Assert.assertNotNull("Data on demand for 'University' failed to initialize correctly", dod.getRandomUniversity());
        long count = com.ug.domain.University.countUniversitys();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'University', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.ug.domain.University> result = com.ug.domain.University.findAllUniversitys();
        org.junit.Assert.assertNotNull("Find all method for 'University' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'University' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UniversityIntegrationTest.testFindUniversityEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'University' failed to initialize correctly", dod.getRandomUniversity());
        long count = com.ug.domain.University.countUniversitys();
        if (count > 20) count = 20;
        java.util.List<com.ug.domain.University> result = com.ug.domain.University.findUniversityEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'University' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'University' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UniversityIntegrationTest.testFlush() {
        com.ug.domain.University obj = dod.getRandomUniversity();
        org.junit.Assert.assertNotNull("Data on demand for 'University' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'University' failed to provide an identifier", id);
        obj = com.ug.domain.University.findUniversity(id);
        org.junit.Assert.assertNotNull("Find method for 'University' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUniversity(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'University' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UniversityIntegrationTest.testMerge() {
        com.ug.domain.University obj = dod.getRandomUniversity();
        org.junit.Assert.assertNotNull("Data on demand for 'University' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'University' failed to provide an identifier", id);
        obj = com.ug.domain.University.findUniversity(id);
        boolean modified =  dod.modifyUniversity(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.ug.domain.University merged = (com.ug.domain.University) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'University' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UniversityIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'University' failed to initialize correctly", dod.getRandomUniversity());
        com.ug.domain.University obj = dod.getNewTransientUniversity(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'University' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'University' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'University' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UniversityIntegrationTest.testRemove() {
        com.ug.domain.University obj = dod.getRandomUniversity();
        org.junit.Assert.assertNotNull("Data on demand for 'University' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'University' failed to provide an identifier", id);
        obj = com.ug.domain.University.findUniversity(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'University' with identifier '" + id + "'", com.ug.domain.University.findUniversity(id));
    }
    
}
