// ActionScript file
import com.views.AboutPage;
import com.views.ConfirmClassified;
import com.views.ContactUs;
import com.views.CorporateLenderClassified;
import com.views.FaceBookLogin;
import com.views.GenaratePassword;
import com.views.HomePage;
import com.views.Login;
import com.views.P2PLenderClassified;
import com.views.PostClassified;
import com.views.PostedSuccess;
import com.views.SignupPage;
import com.views.StudentClassified;
import com.views.WelcomeNote;
import com.views.mentee.MenteeProfile;
import com.views.mentee.MenteeTestimonial;
import com.views.mentor.MentorList;
import com.views.mentor.MentorProfile;
import com.views.mentor.mentorTestimonial;

private var _loginInstance:Login;
private var _welcomeNoteInstance:WelcomeNote;
private var _homeInstance:HomePage;
private var _postClassifiedInstance:PostClassified;
private var _faceBookInstance:FaceBookLogin;
private var _confirmClassifiedInstance:ConfirmClassified;
private var _postConfirmationInstance:PostedSuccess;
private var _signUpInstance:SignupPage;
private var _genPassWord:GenaratePassword;
private var _aboutUsInstance:AboutPage;
private var _studentClassInstance:StudentClassified;
private var _p2plenderInstance:P2PLenderClassified;
private var _corpLenderInstance:CorporateLenderClassified;
private var _contactUsInstance:ContactUs;
private var _faceLoginInstance:FaceBookLogin;
private var _mentorListInstance:MentorList;
private var _mentorInstance:MentorProfile;
private var _mentorAckInstance:mentorTestimonial;
private var _menteeInstance:MenteeProfile;
private var _menteeAckInstance:MenteeTestimonial;
