// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ug.domain;

import java.io.Serializable;

privileged aspect WeblogPK_Roo_Serializable {
    
    declare parents: WeblogPK implements Serializable;
    
    private static final long WeblogPK.serialVersionUID = 1L;
    
}
