// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ug.domain;

import com.ug.domain.GuarantorDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GuarantorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GuarantorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GuarantorIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: GuarantorIntegrationTest: @Transactional;
    
    @Autowired
    private GuarantorDataOnDemand GuarantorIntegrationTest.dod;
    
    @Test
    public void GuarantorIntegrationTest.testCountGuarantors() {
        org.junit.Assert.assertNotNull("Data on demand for 'Guarantor' failed to initialize correctly", dod.getRandomGuarantor());
        long count = com.ug.domain.Guarantor.countGuarantors();
        org.junit.Assert.assertTrue("Counter for 'Guarantor' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GuarantorIntegrationTest.testFindGuarantor() {
        com.ug.domain.Guarantor obj = dod.getRandomGuarantor();
        org.junit.Assert.assertNotNull("Data on demand for 'Guarantor' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Guarantor' failed to provide an identifier", id);
        obj = com.ug.domain.Guarantor.findGuarantor(id);
        org.junit.Assert.assertNotNull("Find method for 'Guarantor' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Guarantor' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GuarantorIntegrationTest.testFindAllGuarantors() {
        org.junit.Assert.assertNotNull("Data on demand for 'Guarantor' failed to initialize correctly", dod.getRandomGuarantor());
        long count = com.ug.domain.Guarantor.countGuarantors();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Guarantor', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.ug.domain.Guarantor> result = com.ug.domain.Guarantor.findAllGuarantors();
        org.junit.Assert.assertNotNull("Find all method for 'Guarantor' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Guarantor' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GuarantorIntegrationTest.testFindGuarantorEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Guarantor' failed to initialize correctly", dod.getRandomGuarantor());
        long count = com.ug.domain.Guarantor.countGuarantors();
        if (count > 20) count = 20;
        java.util.List<com.ug.domain.Guarantor> result = com.ug.domain.Guarantor.findGuarantorEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Guarantor' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Guarantor' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GuarantorIntegrationTest.testFlush() {
        com.ug.domain.Guarantor obj = dod.getRandomGuarantor();
        org.junit.Assert.assertNotNull("Data on demand for 'Guarantor' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Guarantor' failed to provide an identifier", id);
        obj = com.ug.domain.Guarantor.findGuarantor(id);
        org.junit.Assert.assertNotNull("Find method for 'Guarantor' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGuarantor(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Guarantor' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GuarantorIntegrationTest.testMerge() {
        com.ug.domain.Guarantor obj = dod.getRandomGuarantor();
        org.junit.Assert.assertNotNull("Data on demand for 'Guarantor' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Guarantor' failed to provide an identifier", id);
        obj = com.ug.domain.Guarantor.findGuarantor(id);
        boolean modified =  dod.modifyGuarantor(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.ug.domain.Guarantor merged = (com.ug.domain.Guarantor) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Guarantor' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GuarantorIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Guarantor' failed to initialize correctly", dod.getRandomGuarantor());
        com.ug.domain.Guarantor obj = dod.getNewTransientGuarantor(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Guarantor' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Guarantor' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Guarantor' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GuarantorIntegrationTest.testRemove() {
        com.ug.domain.Guarantor obj = dod.getRandomGuarantor();
        org.junit.Assert.assertNotNull("Data on demand for 'Guarantor' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Guarantor' failed to provide an identifier", id);
        obj = com.ug.domain.Guarantor.findGuarantor(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Guarantor' with identifier '" + id + "'", com.ug.domain.Guarantor.findGuarantor(id));
    }
    
}
